version: 1

formatters:
  defaultFormatter:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y/%m/%d %H:%M:%S'

loggers:
  file:
    handlers: [fileRotatingHandler]
    level: DEBUG
    qualname: file
    propagate: no

  console:
    handlers: [consoleHandler]
    level: DEBUG
    qualname: console
    propagate: no

handlers:
  fileRotatingHandler:
    formatter: defaultFormatter
    class: loggerclass.logger_class.MyRotatingFileHandler
    level: DEBUG
    filename: python_logging.log
    encoding: utf8
    when: 'S'
    interval: 86400
    backupCount: 30
    maxBytes: 5242880
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: defaultFormatter
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [fileRotatingHandler,consoleHandler]